name: Release CI

on:
  push:
    tags:
      - "v*" # 触发条件：标签以 v 开头，例如 v1.0.0
  workflow_dispatch:

jobs:
  # 创建 Release
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

  # 构建 Electron 应用
  build-app:
    needs: create-release
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows-latest
            command: pnpm run build:win
            artifact: "dist/*.exe"
          - platform: macos-latest
            command: pnpm run build:mac
            artifact: "dist/*.dmg"

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Electron app
        run: ${{ matrix.command }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: electron-build-${{ matrix.platform }}
          path: ${{ matrix.artifact }}
